# Generated by Django 5.1 on 2024-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=1000)),
                ("short_url", models.CharField(max_length=100)),
                ("created", models.DateField()),
            ],
        ),
    ]
