# Generated by Django 5.1 on 2024-08-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("url_short", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="short_url",
            new_name="short_code",
        ),
    ]
