# Generated by Django 5.1 on 2024-08-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_short", "0002_rename_short_url_url_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="created",
            field=models.DateTimeField(),
        ),
    ]
