# Generated by Django 5.0.7 on 2024-09-21 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_short", "0002_alter_userusage_last_reset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userusage",
            name="last_reset",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
